name: Build Workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev pkg-config

      - name: Set up Rust
        run: rustup default stable

      - name: Install Clippy
        run: rustup component add clippy

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run unit tests
        run: cargo test --all

      - name: Compile (Release build)
        run: cargo build --release
