name: Build Workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: jorgeg1016/scenario-runner:build
